audit_header: false
title: Canton Real Estate Video Blog with Amy Wengerd
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Amy Wengerd
  title:
  license_number:
  about_markdown: |
    It's quite simple. You deserve the Unexpected Extras and unparalleled service my team provides. Whether buying or selling, I will ensure that not only your needs are met but that your expectations are blown away. My team employs a high tech yet hands on approach with each and every one of our clients. As a valued client, you will become part of my real estate family and experience the difference from the very first meeting. For our sellers, we employ a state of the art, creative marketing plan to ensure our homeowners get the most money possible from their home sale. Not only that, but that the process is enjoyable along the way!
  market: Canton
  brand: The Amy Wengerd Group
  brokerage: RE/MAX Crossroads
  address: 4522 Fulton Dr. NW Canton, OH 44718
  address2: Office in Fairlawn, OH as well.
  phone: 330-617-8230
  phone_type:
  phone2:
  phone2_type:
  email: Amy@SoldByWengerd.com
  url: http://www.AmysGuarantee.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.amysguarantee.com/
  second_CTA_text: Home Search
  second_CTA_URL: http://search.amysguarantee.com/?ls=Active&startrow=1&maxrows=50&sort=date_listed_desc&map_tl_lat=42.500603252945815&map_tl_lng=-85.78812874609378&map_br_lat=39.994111795225386&map_br_lng=-77.33414925390628&redraw_map_bounds=false

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.amysguarantee.com/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://search.amysguarantee.com/?ls=Active&startrow=1&maxrows=50&sort=date_listed_desc&map_tl_lat=42.500603252945815&map_tl_lng=-85.78812874609378&map_br_lat=39.994111795225386&map_br_lng=-77.33414925390628&redraw_map_bounds=false

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/SOLDBYWENGERD
  linkedin_url: https://www.linkedin.com/pub/amy-wengerd/71/311/33
  gplus_url: https://plus.google.com/u/0/103459991150243788156
  youtube_url: https://www.youtube.com/channel/UCmYFsifL10rSH02OWpD75Mg
  twitter_url: https://twitter.com/amywengerd
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Amy-Wengerd/
  trulia_url: http://www.trulia.com/profile/amy-wengerd-realty-group-agent-north-canton-oh-81829/overview
  yelp_url: http://www.yelp.com/biz/amy-wengerd-realty-group-canton
  podcast_url:

podcast:
  title: 'Real Estate Podcast with Amy Wengerd'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Canton/Akron Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#bda287'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(238, 238, 238, .75)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
